package com.eshare.tunnel.database;

import com.eshare.domain.creditlimit.CustomerLimit;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface CustomerLimitTunnel {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_quota
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_quota
     *
     * @mbggenerated
     */
    int insert(CustomerLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_quota
     *
     * @mbggenerated
     */
    int insertSelective(CustomerLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_quota
     *
     * @mbggenerated
     */
    CustomerLimit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_quota
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_quota
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerLimit record);

    /**
     * 此方法返回满足条件的记录数;<br/>
     * 此返回条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> t_customer_quota
     *
     * @mbg.generated Mon Dec 11 18:23:07 CST 2019
     */
    Integer countByModelSelective(@Param("cond") CustomerLimit cond, @Param("strict") boolean strict);

    /**
     * 此方法删除满足条件的记录数;<br/>
     * 此条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> t_customer_quota
     *
     * @mbg.generated Mon Dec 11 18:23:07 CST 2019
     */
    Integer deleteByModelSelective(@Param("cond") CustomerLimit cond, @Param("strict") boolean strict);

    /**
     * 此方法根据cond设置条件更新model中设置的字段值;<br/>
     * 此条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table<br/> t_customer_quota
     *
     * @mbg.generated Mon Dec 11 18:23:07 CST 2019
     */
    Integer updateByModelSelective(@Param("cond") CustomerLimit cond, @Param("strict") boolean strict, @Param("model") CustomerLimit model);

    /**
     * 此方法返回满足条件的单条记录.<br/>
     * 此返回条件判断其值不为 null且不为空'';<br/>
     * 若strict为true则精确匹配所有值,若为false则模糊匹配所有类型为String的值;<br/>
     * 注意：java的Date不能完成匹配Oracle Date类型，即insert date into table 然后使用同一值date select是取不到对应记录的.<br/>
     * <p>
     * This method was generated by MyBatis Generator.<br/>
     * This method corresponds to the database table t_customer_quota
     *
     * @mbg.generated Mon Dec 11 18:23:07 CST 2019
     */
    CustomerLimit selectByModelSelective(@Param("cond") CustomerLimit cond, @Param("strict") boolean strict);
}
